### ISSUE TITLE
Payment method dont add on front form in woocommerce

### ISSUE THREAD

**Issue by mathieuworoniecki** [DePayFi/web3-woocommerce-depay-payments#11]
The method of payment dont show in woocommerce
![image](https://github.com/DePayFi/web3-woocommerce-depay-payments/assets/6191226/86497130-6a7c-4db6-83ca-c81c9ee4204a)

![image](https://github.com/DePayFi/web3-woocommerce-depay-payments/assets/6191226/28f5edc5-7ebb-40f9-acdf-ae609b2001e2)

**Comment by 0xNe0x1** [comment]
Can you share a link to that store?

**Comment by Alzok** [comment]
decathlonag2r.com
[SystemStatusReport_decathlonag2r.com_2023-11-28T19-16-17.txt](https://github.com/DePayFi/web3-woocommerce-depay-payments/files/13492225/SystemStatusReport_decathlonag2r.com_2023-11-28T19-16-17.txt)

**Comment by 0xNe0x1** [comment]
Thanks for reporting this. This seems to fail since WooCommerce latest update to the "one-checkout" page. We are actively working on a fix and will let you know once it's ready.

**Comment by 0xNe0x1** [comment]
Thanks for your patience. We've just released version v2.6.0 of the DePay Payments plugin for WooCommerce. It fully integrates "block support" now and should show up in your store (after upgrade)

![Screenshot 2023-11-29 at 12 00 30](https://github.com/DePayFi/web3-woocommerce-depay-payments/assets/16412772/e144d022-a339-4bec-ac0a-4debd26b8f5a)

We remain available in case you have further findings or feedback (here or on discord).
