### ISSUE TITLE
Payment icons float left instead of right

### ISSUE THREAD

**Issue by mdahamshi** [DePayFi/web3-woocommerce-depay-payments#12]
Hey
I have a problem with DePay in my woocomerce store (taptip.shop), the icons float left instead of right like the reset of payments:
![Screenshot_20240422_093852](https://github.com/DePayFi/web3-woocommerce-depay-payments/assets/24778772/83c1ec9f-a7d2-4d2a-8c21-bbc152de5165)
I noticed that you add a <style> to the .payment_method_icons span, if I remove it everything looks good.

can you check please why you added this style tag ?

**Comment by 0xNe0x1** [comment]
Hi there,

We are looking into this, can you let us know which theme you are using?

**Comment by mdahamshi** [comment]
> Hi there,
> 
> We are looking into this, can you let us know which theme you are using?

Blocksy

**Comment by mdahamshi** [comment]
I found the code that adds this style tag, I can remove it and make a pull request

**Comment by 0xNe0x1** [comment]
This might just fixes the problem for your theme only, we will prepare a fix that will be tested against multiple themes.

Thanks for the effort. We will keep you updated.

**Comment by mdahamshi** [comment]
I don't know why you added this style tag in the first place ? I saw a couple of payment plugins and they don't adds this tag.
Please try removing it and check if  the problem occurs at any theme.
Let me know if you want any help

**Comment by 0xNe0x1** [comment]
Long story... we needed to patch some styles while woocommerce block checkouts where still in beta...

We've switched to what we consider standard placement of payment gateway icons in `v2.10.8`.

Please update and let us know if this new version fixes the problem for you.

**Comment by mdahamshi** [comment]
ALl right now thanks

**Comment by 0xNe0x1** [comment]
If you are happy with our plugin and our service, please leave a rating ⭐⭐⭐⭐⭐

- on Wordpress.org: https://wordpress.org/support/plugin/depay-payments-for-woocommerce/reviews/

and

- on WooCommerce: https://woocommerce.com/products/depay-payments/#reviews-start

Thank you.
